apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-controller
  template:
    metadata:
      labels:
        app: k8s-controller
    spec:
      containers:
        - name: k8s-controller
          image: <your-image>
          ports:
            - containerPort: 8080
