apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-container
        image: busybox:latest
        command: ["sh", "-c", "while true; do echo Hello, Kubernetes!; sleep 3600; done"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
