apiVersion: v1
kind: Pod
metadata:
  name: helloworld-pod
spec:
  containers:
  - name: helloworld-container
    image: busybox:latest
    command: ["sh", "-c", "while true; do echo Hello, Kubernetes!; sleep 3600; done"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
